import { describe, expect, test } from "bun:test";
import { packArchive } from "../../../src/archive/pack.ts";
import { unpackArchive } from "../../../src/archive/unpack.ts";

/**
 * Differential test against the real `tar` package (the thing this
 * project's archive side replaces) — same pattern as the image golden
 * suite. A real archive built by `tar` (fixtures/reference/archives/
 * reference.tar, generated by scripts/gen-fixtures.ts) is readable by
 * KilnForge's own unpackArchive(), and KilnForge's own packArchive()
 * output is readable back by the real `tar` package — proving
 * interoperability in both directions, not just self-consistency.
 */
describe("golden: archive interop with the real tar package", () => {
  test("KilnForge's unpackArchive reads a real tar-package-produced archive correctly", async () => {
    const bytes = new Uint8Array(await Bun.file("fixtures/reference/archives/reference.tar").arrayBuffer());
    const entries = await unpackArchive(bytes);
    const byName = Object.fromEntries(entries.map((e) => [e.name, new TextDecoder().decode(e.data)]));
    expect(byName["one.txt"]).toBe("first file contents");
    expect(byName["two.txt"]).toBe("second file, a bit longer than the first one");
  });

  test("a real tar package can read KilnForge's own packArchive output", async () => {
    const tar = await import("tar");
    const bytes = await packArchive([
      { name: "hello.txt", data: new TextEncoder().encode("hello from kilnforge") },
      { name: "data.bin", data: new Uint8Array([1, 2, 3, 4, 5]) },
    ]);

    const tmpFile = `/tmp/kilnforge-golden-${Date.now()}.tar`;
    const tmpDir = `/tmp/kilnforge-golden-extract-${Date.now()}`;
    await Bun.write(tmpFile, bytes);
    const fs = await import("node:fs/promises");
    await fs.mkdir(tmpDir, { recursive: true });

    await tar.extract({ file: tmpFile, cwd: tmpDir });

    const helloContent = await fs.readFile(`${tmpDir}/hello.txt`, "utf8");
    expect(helloContent).toBe("hello from kilnforge");
    const dataContent = await fs.readFile(`${tmpDir}/data.bin`);
    expect(Array.from(dataContent)).toEqual([1, 2, 3, 4, 5]);

    await fs.rm(tmpFile, { force: true });
    await fs.rm(tmpDir, { recursive: true, force: true });
  });

  test("round trips a real Bun.Archive-produced archive through the real tar package too", async () => {
    const bunArchive = new Bun.Archive({ "via-bun.txt": "made by Bun.Archive" });
    const bytes = await bunArchive.bytes();

    const tar = await import("tar");
    const tmpFile = `/tmp/kilnforge-bun-golden-${Date.now()}.tar`;
    const tmpDir = `/tmp/kilnforge-bun-golden-extract-${Date.now()}`;
    await Bun.write(tmpFile, bytes);
    const fs = await import("node:fs/promises");
    await fs.mkdir(tmpDir, { recursive: true });

    await tar.extract({ file: tmpFile, cwd: tmpDir });
    const content = await fs.readFile(`${tmpDir}/via-bun.txt`, "utf8");
    expect(content).toBe("made by Bun.Archive");

    await fs.rm(tmpFile, { force: true });
    await fs.rm(tmpDir, { recursive: true, force: true });
  });
});
